#ifndef MAP_SCRIPTS_H
#define MAP_SCRIPTS_H

#include <genesis.h>

/* Generated by tools/extract_map_scripts.py from zanac.asm DB lines. */
#define MAP_BLOB_BASE      0x9B64
#define MAP_BLOB_END       0xBE26
#define MAP_BLOB_LEN       8899
#define MAP_SCRIPT_COUNT   9
#define MAP_PTR_TABLE_MSX  0x945C
#define MAP_DEFAULT_ROUND  1
#define MAP_HAS_CHARSET    1
#define TILE_TABLES_MSX    0xA444

/* LAB_92af ending stream pointer (round 0 credits). */
#define MAP_ENDING_STREAM  0xA6F4

/* ptr table @0x945C: index i is round (8-i). idx 8 = round 0 / ending. */
extern const u16 map_script_ptrs[MAP_SCRIPT_COUNT];
extern const u16 map_script_lens[MAP_SCRIPT_COUNT];

/* The level blob lives in res/map_blob.bin (SGDK BIN map_blob). */

#endif
