#ifndef SOUND_DATA_H
#define SOUND_DATA_H

#include <genesis.h>

/* Generated by tools/extract_sound.py from zanac.asm DB lines. */
#define SOUND_BLOB_BASE    0x5234
#define SOUND_BLOB_END     0x5A10
#define SOUND_BLOB_LEN     2013
#define SOUND_PTR_TABLE    0x5234
#define SOUND_DUR_TABLE    0x526C
#define SOUND_CURVE_TABLE  0x527D
#define SOUND_EVENT_MAX    27

/* 12-semitone AY period base @0x51F0 (init_psg_freq_table). */
static const u16 k_psg_period_base[12] = {
    0x0FFC, 0x0F1C, 0x0E40, 0x0D74, 0x0CB4, 0x0BFC, 0x0B50, 0x0AAC, 0x0A14, 0x0984, 0x08FC, 0x0878
};

/* res/sound_blob.bin via SGDK BIN sound_blob */
extern const u8 sound_blob[];

#endif
