#ifndef TITLE_LOGO_H
#define TITLE_LOGO_H

#include <genesis.h>

/* Generated by tools/extract_logo.py from zanac.asm. */
#define LOGO_TILE_MSX_FIRST  0xB0
#define LOGO_TILE_COUNT      61
#define LOGO_ROW_STRIDE      25
#define LOGO_ROW_COUNT       5
#define LOGO_DRAW_COLS       18
#define LOGO_DRAW_ROWS       5
#define LOGO_PX_X            40
#define LOGO_PX_Y            72

extern const u8 logo_tile_rows[LOGO_ROW_COUNT * LOGO_ROW_STRIDE];
extern const u8 logo_swirl_path[56];

#endif
