/* Generated by tools/extract_vel_dir.py from zanac.asm. Do not edit. */
#ifndef VEL_DIR_H
#define VEL_DIR_H

#include <genesis.h>

/* MSX set_velocity_from_dir 0x4CF7 unit vectors (magnitude 128, 8.8).
 * Multiply by an entity speed byte (IX+0x17) to get an 8.8 velocity.
 * The player ship uses 5 (player_ship_handler 0x75F3). */
#define VEL_DIR_COUNT   16
#define VEL_SEL_COUNT   9
#define SHIP_SPEED_BYTE 5

extern const s16 vel_dir_y[VEL_DIR_COUNT];
extern const s16 vel_dir_x[VEL_DIR_COUNT];
extern const u8  vel_sel_dir[VEL_SEL_COUNT];

#endif
