#!/usr/bin/env python3
"""Extract the MSX 16-direction unit-velocity table into the MD port.

Reads DB lines from zanac.asm (load address in the trailing comment) and emits
src/data/vel_dir.c + inc/vel_dir.h.

Axis order (important -- see notes below):
    vel_dir_table 0x4D65 holds 16 entries of 4 bytes = two signed 16-bit LE
    words. set_velocity_from_dir (0x4CF7) stores word0 into IX+0x08/0x09 and
    word1 into IX+0x0A/0x0B. player_ship_update (0x7628/0x764E) adds IX+0x08/09
    to the position whose integer byte is IX+0x01 and IX+0x0A/0B to IX+0x02.
    The airborne spawn helper 0x71C5 writes IX+0x01 = 0 and IX+0x02 = random in
    [0x28,0xC6], i.e. enemies enter from the top at a random column, so
    IX+0x01 is Y and IX+0x02 is X. Therefore word0 is the Y component and word1
    is the X component, and direction 4 points straight down.

    Note that zanac-re's kb/data/vel_dir_table.md labels the two words the other
    way round ("X-component then Y-component", dir 0 = down). That label is
    inconsistent with the store order above and with 0x71C5; the ordering used
    here is what the code actually does.

Usage (from zanac-md):
    python tools/extract_vel_dir.py
    python tools/extract_vel_dir.py --asm PATH --out .
"""
from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

VEL_DIR_TABLE = 0x4D65
VEL_DIR_LEN = 64          # 16 dirs x 4 bytes
XVEL_TABLE = 0x7758       # E10C selector 0-8 -> 16-dir index
XVEL_LEN = 9
SHIP_SPEED = 5            # player_ship_handler: LD (IX+0x17), 0x05 @ 0x75F3
ROM_END = 0xC000

DB_RE = re.compile(r"^\s+DB\s+(.+);\s*0x([0-9A-Fa-f]{4})", re.I)
HEX_RE = re.compile(r"0x([0-9A-Fa-f]{1,2})\b", re.I)
SPEED_RE = re.compile(r"LD\s+\(IX\+0x17\),\s*0x0?5\s*;\s*0x75f3", re.I)


def parse_db_bytes(path: Path) -> tuple[bytearray, bytearray, str]:
    """Return (rom, filled, full_text) built from every DB line in the asm."""
    rom = bytearray(ROM_END)
    filled = bytearray(ROM_END)
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        m = DB_RE.match(line)
        if not m:
            continue
        addr = int(m.group(2), 16)
        for i, h in enumerate(HEX_RE.findall(m.group(1))):
            a = addr + i
            if 0 <= a < ROM_END:
                rom[a] = int(h, 16) & 0xFF
                filled[a] = 1
    return rom, filled, text


def need(filled: bytearray, lo: int, length: int, what: str) -> None:
    missing = [hex(a) for a in range(lo, lo + length) if not filled[a]]
    if missing:
        sys.exit(f"error: {what}: no DB coverage for {len(missing)} byte(s): "
                 f"{', '.join(missing[:8])}")


def s16le(rom: bytearray, addr: int) -> int:
    v = rom[addr] | (rom[addr + 1] << 8)
    return v - 0x10000 if v & 0x8000 else v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--asm", default="../zanac-re/source/zanac.asm")
    ap.add_argument("--out", default=".")
    args = ap.parse_args()

    asm = Path(args.asm)
    if not asm.is_file():
        return int(bool(sys.stderr.write(f"error: no asm at {asm}\n"))) or 2
    out = Path(args.out)

    rom, filled, text = parse_db_bytes(asm)
    need(filled, VEL_DIR_TABLE, VEL_DIR_LEN, "vel_dir_table 0x4D65")
    need(filled, XVEL_TABLE, XVEL_LEN, "xvel_table 0x7758")

    if not SPEED_RE.search(text):
        sys.exit("error: could not confirm 'LD (IX+0x17), 0x05' at 0x75F3; "
                 "refusing to guess the ship speed byte")

    vy = [s16le(rom, VEL_DIR_TABLE + d * 4 + 0) for d in range(16)]
    vx = [s16le(rom, VEL_DIR_TABLE + d * 4 + 2) for d in range(16)]
    sel = [rom[XVEL_TABLE + i] for i in range(XVEL_LEN)]

    # Numeric self-check: the table must be a unit circle of radius ~128, so
    # diagonals may not be faster than cardinals.
    mags = [math.hypot(vx[d], vy[d]) for d in range(16)]
    lo, hi = min(mags), max(mags)
    if hi - lo > 1.0:
        sys.exit(f"error: table is not normalised (magnitude {lo:.2f}..{hi:.2f})")
    print(f"vel_dir_table: 16 dirs, magnitude {lo:.2f}..{hi:.2f} "
          f"(spread {hi - lo:.2f})")
    print(f"ship speed byte 0x75F3 = {SHIP_SPEED} -> "
          f"{lo * SHIP_SPEED / 256.0:.4f}..{hi * SHIP_SPEED / 256.0:.4f} px/frame")
    for d in range(16):
        print(f"  dir {d:2d}: Y={vy[d]:5d} X={vx[d]:5d}  |v|={mags[d]:7.3f}")

    def row(vals: list[int]) -> str:
        out_lines = []
        for i in range(0, 16, 8):
            out_lines.append("    " + ", ".join(f"{v:5d}" for v in vals[i:i + 8]))
        return ",\n".join(out_lines)

    banner = ("/* Generated by tools/extract_vel_dir.py from zanac.asm. "
              "Do not edit. */\n")

    c_src = (
        banner
        + '#include "vel_dir.h"\n\n'
        + "/* vel_dir_table 0x4D65, magnitude 128, 8.8 fixed point.\n"
        + " * word0 -> Y (IX+0x08/09 -> IX+0x01), word1 -> X (IX+0x0A/0B -> IX+0x02).\n"
        + " * dir 0 = right, 4 = down, 8 = left, 12 = up; 22.5 deg per step. */\n"
        + f"const s16 vel_dir_y[{16}] = {{\n{row(vy)}\n}};\n\n"
        + f"const s16 vel_dir_x[{16}] = {{\n{row(vx)}\n}};\n\n"
        + "/* xvel_table 0x7758: E10C selector 0-8 -> 16-dir index. */\n"
        + f"const u8 vel_sel_dir[{XVEL_LEN}] = {{\n    "
        + ", ".join(f"0x{v:02X}" for v in sel)
        + "\n};\n"
    )

    h_src = (
        banner
        + "#ifndef VEL_DIR_H\n#define VEL_DIR_H\n\n"
        + "#include <genesis.h>\n\n"
        + "/* MSX set_velocity_from_dir 0x4CF7 unit vectors (magnitude 128, 8.8).\n"
        + " * Multiply by an entity speed byte (IX+0x17) to get an 8.8 velocity.\n"
        + " * The player ship uses 5 (player_ship_handler 0x75F3). */\n"
        + f"#define VEL_DIR_COUNT   {16}\n"
        + f"#define VEL_SEL_COUNT   {XVEL_LEN}\n"
        + f"#define SHIP_SPEED_BYTE {SHIP_SPEED}\n\n"
        + "extern const s16 vel_dir_y[VEL_DIR_COUNT];\n"
        + "extern const s16 vel_dir_x[VEL_DIR_COUNT];\n"
        + "extern const u8  vel_sel_dir[VEL_SEL_COUNT];\n\n"
        + "#endif\n"
    )

    c_path = out / "src" / "data" / "vel_dir.c"
    h_path = out / "inc" / "vel_dir.h"
    c_path.write_text(c_src, encoding="utf-8")
    h_path.write_text(h_src, encoding="utf-8")
    print(f"wrote {c_path} ({len(c_src)} B) and {h_path} ({len(h_src)} B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
