/* Generated by tools/extract_vel_dir.py from zanac.asm. Do not edit. */
#include "vel_dir.h"

/* vel_dir_table 0x4D65, magnitude 128, 8.8 fixed point.
 * word0 -> Y (IX+0x08/09 -> IX+0x01), word1 -> X (IX+0x0A/0B -> IX+0x02).
 * dir 0 = right, 4 = down, 8 = left, 12 = up; 22.5 deg per step. */
const s16 vel_dir_y[16] = {
        0,    48,    90,   118,   128,   118,    90,    48,
        0,   -48,   -90,  -118,  -128,  -118,   -90,   -48
};

const s16 vel_dir_x[16] = {
      128,   118,    90,    48,     0,   -48,   -90,  -118,
     -128,  -118,   -90,   -48,     0,    48,    90,   118
};

/* xvel_table 0x7758: E10C selector 0-8 -> 16-dir index. */
const u8 vel_sel_dir[9] = {
    0x06, 0x08, 0x0A, 0x04, 0x0C, 0x0C, 0x02, 0x00, 0x0E
};
